INSERT INTO yoda (OdaNo,OdaKapasite,odadolu) VALUES ('101','2','0');
INSERT INTO yoda (OdaNo,OdaKapasite,odadolu) VALUES ('102','2','0');
INSERT INTO yoda (OdaNo,OdaKapasite,odadolu) VALUES ('103','2','0');
INSERT INTO yoda (OdaNo,OdaKapasite,odadolu) VALUES ('104','2','0');
INSERT INTO yoda (OdaNo,OdaKapasite,odadolu) VALUES ('105','2','0');
INSERT INTO yoda (OdaNo,OdaKapasite,odadolu) VALUES ('201','3','0');
INSERT INTO yoda (OdaNo,OdaKapasite,odadolu) VALUES ('202','3','0');
INSERT INTO yoda (OdaNo,OdaKapasite,odadolu) VALUES ('203','3','0');
INSERT INTO yoda (OdaNo,OdaKapasite,odadolu) VALUES ('204','3','0');
INSERT INTO yoda (OdaNo,OdaKapasite,odadolu) VALUES ('205','3','0');
INSERT INTO yoda (OdaNo,OdaKapasite,odadolu) VALUES ('301','4','0');
INSERT INTO yoda (OdaNo,OdaKapasite,odadolu) VALUES ('302','4','0');
INSERT INTO yoda (OdaNo,OdaKapasite,odadolu) VALUES ('303','4','0');
INSERT INTO yoda (OdaNo,OdaKapasite,odadolu) VALUES ('304','4','0');
INSERT INTO yoda (OdaNo,OdaKapasite,odadolu) VALUES ('305','4','0');
INSERT INTO yoda (OdaNo,OdaKapasite,odadolu) VALUES ('401','6','0');
INSERT INTO yoda (OdaNo,OdaKapasite,odadolu) VALUES ('402','6','0');
INSERT INTO yoda (OdaNo,OdaKapasite,odadolu) VALUES ('403','6','0');
INSERT INTO yoda (OdaNo,OdaKapasite,odadolu) VALUES ('404','6','0');
INSERT INTO yoda (OdaNo,OdaKapasite,odadolu) VALUES ('405','6','0');

INSERT INTO ybolumler (BolumAd) VALUES ('Bilgisayar Müh.');
INSERT INTO ybolumler (BolumAd) VALUES ('Elektrik Müh.');
INSERT INTO ybolumler (BolumAd) VALUES ('Çevre Müh.');
INSERT INTO ybolumler (BolumAd) VALUES ('Mimarlık');
INSERT INTO ybolumler (BolumAd) VALUES ('Hukuk');
INSERT INTO ybolumler (BolumAd) VALUES ('Tıp');
INSERT INTO ybolumler (BolumAd) VALUES ('Odyoloji');
INSERT INTO ybolumler (BolumAd) VALUES ('Gazetecilik');
INSERT INTO ybolumler (BolumAd) VALUES ('Diş Hekimliği');
INSERT INTO ybolumler (BolumAd) VALUES ('Öğretmenlik');
INSERT INTO ybolumler (BolumAd) VALUES ('Odyoloji');
INSERT INTO ybolumler (BolumAd) VALUES ('Endüstri Müh.');
INSERT INTO ybolumler (BolumAd) VALUES ('Kimya');
INSERT INTO ybolumler (BolumAd) VALUES ('Biyoloji');
INSERT INTO ybolumler (BolumAd) VALUES ('Fizik');
INSERT INTO ybolumler (BolumAd) VALUES ('Matematik');
INSERT INTO ybolumler (BolumAd) VALUES ('Yazılım Müh.');
INSERT INTO ybolumler (BolumAd) VALUES ('U. Ticaret');
INSERT INTO ybolumler (BolumAd) VALUES ('Gıda Mühendisliği');

Insert into ADMIN (ADMINID,ADMINKULLANICI,ADMINSIFRE) values ('1','admin','1234');

