--TRIGGER KOMUTLARI
create or replace NONEDITIONABLE TRIGGER ADMIN_TRG 
BEFORE INSERT ON ADMIN 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ADMINID IS NULL THEN
      SELECT ADMIN_SEQ.NEXTVAL INTO :NEW.ADMINID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;


create or replace NONEDITIONABLE TRIGGER YBOLUMLER_TRG 
BEFORE INSERT ON YBOLUMLER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.BOLUMID IS NULL THEN
      SELECT YBOLUMLER_SEQ7.NEXTVAL INTO :NEW.BOLUMID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;


create or replace NONEDITIONABLE TRIGGER YOGRENCI_TRG 
BEFORE INSERT ON YOGRENCI 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.OGRID IS NULL THEN
      SELECT YOGRENCI_SEQ3.NEXTVAL INTO :NEW.OGRID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;


CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."YOKLAMA_TRG" 
BEFORE INSERT ON YOKLAMA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;



create or replace NONEDITIONABLE TRIGGER YYEMEK_TRG 
BEFORE INSERT ON YYEMEK 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.YEMEKID IS NULL THEN
      SELECT YYEMEK_SEQ1.NEXTVAL INTO :NEW.YEMEKID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;


create or replace NONEDITIONABLE TRIGGER YODA_TRG 
BEFORE INSERT ON YODA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ODAID IS NULL THEN
      SELECT YODA_SEQ.NEXTVAL INTO :NEW.ODAID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;



